# Generated by Django 4.2.15 on 2024-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_of_interest', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('gender', models.CharField(max_length=500)),
                ('date_of_birth', models.DateField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=20)),
                ('educational_background', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('learning_mode', models.CharField(max_length=100)),
                ('sponsorship', models.CharField(max_length=50)),
                ('sponsor_relationship', models.CharField(max_length=100)),
                ('sponsor_phone_number', models.CharField(max_length=20)),
                ('how_did_you_hear_about_us', models.CharField(max_length=200)),
            ],
        ),
    ]
