# Generated by Django 4.2.15 on 2024-08-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sponsor_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sponsor_relationship',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
