# Generated by Django 4.2.15 on 2024-08-10 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_alter_user_sponsor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 17, 14, 11, 913889, tzinfo=datetime.timezone.utc)),
        ),
    ]
