# Generated by Django 4.2.15 on 2024-08-10 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_user_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
